### ISSUE TITLE
项目Clone下来不能直接跑起来

### ISSUE THREAD

**Issue by vzardlloo** [icepoint0/angular-4-learn#2]
项目是通过`ng new XXX`创建的，但是直接clone的人将会导致缺少很多的npm包而报错

**Comment by vzardlloo** [comment]
补充，借助IDE(webstorm)可以解决，导入时会提示

**Comment by 100cm** [comment]
直接npm install

**Comment by xiaoCong2014** [comment]
npm install 失败的话 , 用阿里的 cnpm install , 具体怎么用 cnpm 这个工具 , 百度 cnpm 的官方文档
